### PR TITLE
Fix split signature in TuplesHListExercises

### PR DESCRIPTION
**Pull request by durban**

### CODE REVIEW

**Comment by raulraja** [comment]
Great catch @durban . Do you mind also fixing the associated test? https://github.com/scala-exercises/exercises-shapeless/blob/master/src/test/scala/exercises/shapeless/TuplesHListExercisesSpec.scala#L51 Thanks!

**Comment by durban** [comment]
Done.

**Comment by raulraja** [comment]
Awesome, thanks for your contribution!

**Comment by raulraja** [comment]
LGTM

**Pull request merged**
